# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='-', max_length=750),
        ),
    ]
