# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='anon', max_length=200),
        ),
    ]
