# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180203_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plain_text',
        ),
    ]
