# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
