# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stackoverflow_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workplace',
        ),
    ]
