# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180130_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='author',
        ),
        migrations.DeleteModel(
            name='Me',
        ),
    ]
